#!/bin/bash

LABNAME="MISC LAB"

if [[ $# == 0 ]]; then
    echo "========= $LABNAME ========="
    echo "Usage:";
    echo "Build challenge:     ./snippet build";
    echo "Rebuild challenge:   ./snippet rebuild";
    echo "Start challenge:     ./snippet start";
    echo "Stop challenge:      ./snippet stop";
    exit 0
fi

PPC_DOCKERNAME="ppc_lab"

if [[ $1 == "build" ]]; then
    docker build -t $PPC_DOCKERNAME ./PPC;
elif [[ $1 == "rebuild" ]]; then
    docker rmi $PPC_DOCKERNAME;
    docker build -t $PPC_DOCKERNAME ./PPC;
elif [[ $1 == "start" ]]; then
    docker run -p 50000-50008:50000-50008 --name $PPC_DOCKERNAME -d $PPC_DOCKERNAME;
elif [[ $1 == "stop" ]]; then
    docker stop $PPC_DOCKERNAME;
    docker rm $PPC_DOCKERNAME;
fi